name: Download FX Data

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run export_fxrate.py
        run: |
          FXPAIRS_JSON=$(cat fxpairs.json | jq -c .)
          python export_fxrate.py --fxpairs "$FXPAIRS_JSON"

      - name: Push JSONs to 'investment-analyser-data' repo
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          TARGET_REPO="github.com/coldsofttech/investment-analyser-data.git"
          BRANCH="main"
          WORKDIR=$(mktemp -d)
          
          echo "📦 Cloning target repo..."
          git clone --depth 1 --branch $BRANCH https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@$TARGET_REPO $WORKDIR
          
          echo "📂 Creating docs/fxrates folder if missing..."
          mkdir -p $WORKDIR/docs/fxrates
          
          echo "📂 Copying output files..."
          cp -f output/*.json $WORKDIR/docs/fxrates/
          
          cd $WORKDIR
          if git status --porcelain | grep .; then
            git add docs/fxrates/*.json
            git commit -m "📈 Update JSONs in docs/fxrates/ from ${{ github.repository }} at ${{ github.run_id }}"
            git push origin $BRANCH
            echo "✅ JSONs pushed to $TARGET_REPO docs/fxrates/"
          else
            echo "ℹ️ No changes to commit."
          fi
