name: Download Ticker Data

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  split-tickers:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.split.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate matrix chunks
        id: split
        env:
          CHUNK_SIZE: ${{ secrets.CHUNK_SIZE_TICKERS }}
        run: |
          CHUNK_SIZE=${CHUNK_SIZE:-10}
          echo "🔢 Using CHUNK_SIZE=$CHUNK_SIZE"
          MATRIX=$(python split_tickers.py tickers.json "$CHUNK_SIZE")
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  run-fetch:
    needs: split-tickers
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.split-tickers.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run export_stocks.py
        run: |
          python export_stocks.py --tickers "${{ join(matrix.chunk, ',') }}"

      #      - name: Make Output script executable
      #        run: chmod +x scripts/list_outputs.sh
      #
      #      - name: Show Output files
      #        run: scripts/list_outputs.sh

      - name: Push JSONs to target repo
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          TARGET_REPO="${{ secrets.TARGET_REPO }}"
          BRANCH="${{ secrets.TARGET_REPO_BRANCH }}"
          WORKDIR=$(mktemp -d)
          
          echo "📦 Cloning target repo..."
          git clone --depth 1 --branch $BRANCH https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@$TARGET_REPO $WORKDIR
          
          echo "📂 Creating docs/tickers folder if missing..."
          mkdir -p $WORKDIR/docs/tickers
          
          echo "📂 Copying output files..."
          cp -f output/*.json $WORKDIR/docs/tickers/
          
          cd $WORKDIR
          if git status --porcelain | grep .; then
            git add docs/tickers/*.json
            git commit -m "📈 Update JSONs in docs/tickers/ from ${{ github.repository }} at ${{ github.run_id }}"
            git push origin $BRANCH
            echo "✅ JSONs pushed to $TARGET_REPO docs/tickers/"
          else
            echo "ℹ️ No changes to commit."
          fi
