name: Download Ticker Data

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  split-tickers:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.split.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate matrix chunks
        id: split
        run: |
          MATRIX=$(python split_tickers.py tickers.json 6)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  run-fetch:
    needs: split-tickers
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.split-tickers.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run export_stocks.py
        run: |
          python export_stocks.py --tickers "${{ join(matrix.chunk, ',') }}"

      - name: Make Output script executable
        run: chmod +x scripts/list_outputs.sh
      
      - name: Show Output files
        run: scripts/list_outputs.sh
